// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oknvtyxinrdakxrqsfse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbnZ0eXhpbnJkYWt4cnFzZnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTA5NTksImV4cCI6MjA2NDUyNjk1OX0.6Gzh89bhCv6SfcpGdZW2IWdmqd6WNTOkJis4RLAVabU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);